"""CAM 工序的 NC 程序导出。

与基座的 :mod:`toolpath_lab.export.gcode` 相比，这里补上真实机床程序需要的头部：

- 程序号（``O`` 号）与工件坐标系（G54…）；
- 刀具、主轴转速与转向、冷却液；
- 每道工序的注释块（工序名、策略、关键参数），便于现场核对；
- 结尾统一退刀 + 主轴停 + ``M30``。

G 代码子集与基座保持一致（G21/G90/G17 + G0/G1 + F），Fanuc / 三菱 / 新代等常见
控制器都能直接跑。
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Iterable, Sequence

from toolpath_lab.core.path import MoveKind, Toolpath
from toolpath_lab.core.tool import Tool

#: 主轴转向 -> M 代码
SPINDLE_CODES: dict[str, str] = {"cw": "M03", "ccw": "M04"}
#: 冷却 -> M 代码
COOLANT_CODES: dict[str, str] = {"flood": "M08", "mist": "M07", "off": "M09"}


@dataclass(frozen=True, slots=True)
class ProgramHeader:
    """NC 程序头部信息。"""

    program_name: str = "TOOLPATH_LAB"
    program_number: int = 1000
    work_offset: str = "G54"
    spindle_rpm: float = 3000.0
    spindle_direction: str = "cw"
    coolant: str = "flood"
    tool: Tool | None = None
    notes: tuple[str, ...] = ()
    output_comments: bool = True


def program_from_operations(operations: Sequence[tuple[str, Toolpath, dict[str, Any]]],
                            header: ProgramHeader, *,
                            decimals: int = 3) -> str:
    """把若干道工序拼成一个 NC 程序。

    ``operations`` 的每一项是 ``(工序名, 刀路, 该工序的参数)``。
    """

    lines: list[str] = []
    _emit_header(lines, header, total_operations=len(operations))

    for index, (name, toolpath, parameters) in enumerate(operations, start=1):
        _emit_operation_comment(lines, index, name, parameters, header)
        _emit_moves(lines, toolpath, decimals=decimals)
        lines.append("")

    lines.append("(end of program)")
    lines.append(f"G0 Z{_number(50.0, decimals)} (retract)")
    lines.append("M05 (spindle stop)")
    lines.append("M09 (coolant off)")
    lines.append("M30 (program end)")
    return "\n".join(lines) + "\n"


def _emit_header(lines: list[str], header: ProgramHeader, *, total_operations: int) -> None:
    number = max(1, min(int(header.program_number), 99999))
    lines.append(f"O{number:04d} ({header.program_name})")
    if header.output_comments:
        lines.append(f"(program: {header.program_name})")
        lines.append(f"(operations: {total_operations})")
        lines.append("(generated by ToolpathLab)")
        for note in header.notes:
            for chunk in str(note).splitlines():
                lines.append(f"({chunk})")
    lines.append("G21 (mm)")
    lines.append("G90 (absolute)")
    lines.append("G17 (XY plane)")
    lines.append(f"{header.work_offset} (work offset)")
    tool = header.tool
    if tool is not None:
        lines.append(f"(tool: flat end mill D{tool.diameter_mm:g} mm L{tool.length_mm:g} mm)")
    lines.append(f"S{header.spindle_rpm:g} {SPINDLE_CODES.get(header.spindle_direction, 'M03')}")
    coolant = COOLANT_CODES.get(header.coolant, "M08")
    if coolant != "M09":
        lines.append(f"{coolant} (coolant on)")
    lines.append("")


def _emit_operation_comment(lines: list[str], index: int, name: str,
                            parameters: dict[str, Any], header: ProgramHeader) -> None:
    if not header.output_comments:
        lines.append(f"(operation {index}: {name})")
        return
    lines.append(f"(operation {index}: {name})")
    keyword = {
        "spindle_rpm": "S", "feed_mm_per_min": "F", "stepover_mm": "ae",
        "cut_depth_mm": "ap", "stock_allowance_mm": "stock", "finish_allowance_mm": "finish",
        "tool_diameter_mm": "D", "safe_height_mm": "safeZ", "cut_mode": "mode",
    }
    for key, label in keyword.items():
        if key in parameters:
            lines.append(f"({label}: {parameters[key]})")


def _emit_moves(lines: list[str], toolpath: Toolpath, *, decimals: int) -> None:
    last_feed: float | None = None
    last_kind: MoveKind | None = None
    for move in toolpath.moves:
        if move.kind is not MoveKind.RAPID and move.feed_mm_per_min != last_feed:
            last_feed = move.feed_mm_per_min
            last_kind = None
        for point in move.points:
            x, y, z = (float(value) for value in point)
            coordinates = (
                f"X{_number(x, decimals)} Y{_number(y, decimals)} Z{_number(z, decimals)}"
            )
            if move.kind is MoveKind.RAPID:
                lines.append(f"G0 {coordinates}")
            else:
                if last_kind is not MoveKind.CUT and last_kind is not MoveKind.LINK:
                    lines.append(f"F{_number(move.feed_mm_per_min, decimals)}")
                lines.append(f"G1 {coordinates}")
            last_kind = move.kind


def _number(value: float, decimals: int) -> str:
    text = f"{value:.{decimals}f}"
    if "." in text:
        text = text.rstrip("0").rstrip(".")
    return text or "0"


def toolpath_gcode(toolpath: Toolpath, *, program_name: str = "TOOLPATH_LAB",
                   description: Iterable[str] = (), decimals: int = 3) -> str:
    """单条刀路的 NC 程序（没有机床头，供内部/测试使用）。"""

    lines = [f"({program_name})"]
    for item in description:
        lines.append(f"({item})")
    lines.extend(["G21", "G90", "G17", ""])
    _emit_moves(lines, toolpath, decimals=decimals)
    lines.extend(["", "M30"])
    return "\n".join(lines) + "\n"


__all__ = [
    "COOLANT_CODES",
    "ProgramHeader",
    "SPINDLE_CODES",
    "program_from_operations",
    "toolpath_gcode",
]
