"""G-code (NC program) export.

Uses the most common ISO subset: G21/G90/G17, G0 for rapids and G1 with F for cutting, which Fanuc,
Siemens and virtually every hobby controller understand. To add another export format, write a pure
function under export/ and add one branch in server/app.py.

The header always carries a summary read off the toolpath itself plus the strategy's notes, so an NC
file that leaves this program can explain where it came from; `provenance` adds the facts only the
caller knows (coverage, warnings, the echoed request).
"""

from __future__ import annotations

from collections.abc import Iterable

from toolpath_lab.core.path import MoveKind, Toolpath
from toolpath_lab.export.summary import provenance_lines, toolpath_summary_lines


def toolpath_to_gcode(
    toolpath: Toolpath,
    *,
    program_name: str = "TOOLPATH_LAB",
    description: str = "",
    decimals: int = 3,
    provenance: Iterable[str] = (),
) -> str:
    """Render one toolpath as an NC program."""

    lines: list[str] = [f"({program_name})"]
    if description:
        for chunk in description.splitlines():
            lines.append(f"({chunk})")
    lines.append("(generated by ToolpathLab)")
    for chunk in toolpath_summary_lines(toolpath):
        lines.append(f"({chunk})")
    for chunk in provenance_lines(provenance):
        lines.append(f"({chunk})")
    for note in provenance_lines(toolpath.notes):
        lines.append(f"({note})")
    lines.append("G21 (mm)")
    lines.append("G90 (absolute)")
    lines.append("G17 (XY plane)")
    lines.append("")

    number = f"{{:.{decimals}f}}"
    last_feed: float | None = None
    last_kind: MoveKind | None = None

    for move in toolpath.moves:
        if move.kind is not MoveKind.RAPID:
            if move.feed_mm_per_min != last_feed:
                last_feed = move.feed_mm_per_min
                last_kind = None
        for point in move.points:
            x, y, z = (float(value) for value in point)
            coordinates = f"X{number.format(x)} Y{number.format(y)} Z{number.format(z)}"
            if move.kind is MoveKind.RAPID:
                if last_kind is not MoveKind.RAPID:
                    lines.append("(rapid)")
                lines.append(f"G0 {coordinates}")
            else:
                if last_kind is not MoveKind.CUT and last_kind is not MoveKind.LINK:
                    lines.append(f"F{number.format(move.feed_mm_per_min)}")
                lines.append(f"G1 {coordinates}")
            last_kind = move.kind

    lines.append("")
    lines.append("M30")
    return "\n".join(lines) + "\n"
