"""G-code（NC 程序）导出。

用的是最常见的 ISO 子集：G21/G90/G17，快移 G0、切削 G1 带 F，
Fanuc、Siemens 以及绝大多数 hobby 控制器都认。
新增导出格式：在 export/ 下写一个纯函数，再在 server/app.py 里加一个分支即可。
"""

from __future__ import annotations

from math import atan2, degrees, hypot
from typing import Any

from toolpath_lab.core.path import MoveKind, Toolpath


def tool_axis_to_ab(axis: Any) -> tuple[float, float]:
    """将 +Z 为零位的刀轴单位向量转换为 A(方位)/B(倾角) 度数。"""

    x, y, z = (float(value) for value in axis)
    azimuth = 0.0 if hypot(x, y) <= 1e-9 else degrees(atan2(y, x))
    tilt = degrees(atan2(hypot(x, y), z))
    return azimuth, tilt


def toolpath_to_gcode(
    toolpath: Toolpath,
    *,
    program_name: str = "TOOLPATH_LAB",
    description: str = "",
    decimals: int = 3,
    extra_header: dict[str, Any] | None = None,
) -> str:
    """把一条刀路渲染成 NC 程序。"""

    lines: list[str] = [f"({program_name})"]
    if description:
        for chunk in description.splitlines():
            lines.append(f"({chunk})")
    lines.append("(generated by ToolpathLab)")
    for key, value in (extra_header or {}).items():
        lines.append(f"({key}: {value})")
    for note in toolpath.notes:
        lines.append(f"({note})")
    lines.append("G21 (mm)")
    lines.append("G90 (absolute)")
    lines.append("G17 (XY plane)")
    if toolpath.is_oriented:
        lines.append("(five-axis: A=azimuth deg, B=tilt-from-Z deg)")
    if any(move.angular_speed_deg_s is not None for move in toolpath.moves):
        lines.append("(orientation time limits are simulation-only; machine postprocessing required)")
    lines.append("")

    number = f"{{:.{decimals}f}}"
    last_feed: float | None = None
    last_kind: MoveKind | None = None
    previous_azimuth: float | None = None

    for move in toolpath.moves:
        if move.kind is not MoveKind.RAPID:
            if move.feed_mm_per_min != last_feed:
                last_feed = move.feed_mm_per_min
                last_kind = None
        for point_index, point in enumerate(move.points):
            x, y, z = (float(value) for value in point)
            coordinates = f"X{number.format(x)} Y{number.format(y)} Z{number.format(z)}"
            if toolpath.is_oriented:
                azimuth, tilt = tool_axis_to_ab(move.tool_axes[point_index])
                if previous_azimuth is not None:
                    if abs(tilt) < 1e-8:
                        azimuth = previous_azimuth
                    else:
                        azimuth = previous_azimuth + (azimuth - previous_azimuth + 180.0) % 360.0 - 180.0
                previous_azimuth = azimuth
                coordinates += f" A{number.format(azimuth)} B{number.format(tilt)}"
            if move.kind is MoveKind.RAPID:
                if last_kind is not MoveKind.RAPID:
                    lines.append("(rapid)")
                lines.append(f"G0 {coordinates}")
            else:
                if last_kind is not MoveKind.CUT and last_kind is not MoveKind.LINK:
                    lines.append(f"F{number.format(move.feed_mm_per_min)}")
                lines.append(f"G1 {coordinates}")
            last_kind = move.kind

    lines.append("")
    lines.append("M30")
    return "\n".join(lines) + "\n"
