"""G-code（NC 程序）导出。

用的是最常见的 ISO 子集：G21/G90/G17，快移 G0、切削 G1 带 F，
Fanuc、Siemens 以及绝大多数 hobby 控制器都认。
新增导出格式：在 export/ 下写一个纯函数，再在 server/app.py 里加一个分支即可。
"""

from __future__ import annotations

from typing import Any

from toolpath_lab.core.path import MoveKind, Toolpath


def toolpath_to_gcode(
    toolpath: Toolpath,
    *,
    program_name: str = "TOOLPATH_LAB",
    description: str = "",
    decimals: int = 3,
    extra_header: dict[str, Any] | None = None,
) -> str:
    """把一条刀路渲染成 NC 程序。"""

    lines: list[str] = [f"({program_name})"]
    if description:
        for chunk in description.splitlines():
            lines.append(f"({chunk})")
    lines.append("(generated by ToolpathLab)")
    for key, value in (extra_header or {}).items():
        lines.append(f"({key}: {value})")
    for note in toolpath.notes:
        lines.append(f"({note})")
    lines.append("G21 (mm)")
    lines.append("G90 (absolute)")
    lines.append("G17 (XY plane)")
    lines.append("")

    number = f"{{:.{decimals}f}}"
    last_feed: float | None = None
    last_kind: MoveKind | None = None

    for move in toolpath.moves:
        if move.kind is not MoveKind.RAPID:
            if move.feed_mm_per_min != last_feed:
                last_feed = move.feed_mm_per_min
                last_kind = None
        for point in move.points:
            x, y, z = (float(value) for value in point)
            coordinates = f"X{number.format(x)} Y{number.format(y)} Z{number.format(z)}"
            if move.kind is MoveKind.RAPID:
                if last_kind is not MoveKind.RAPID:
                    lines.append("(rapid)")
                lines.append(f"G0 {coordinates}")
            else:
                if last_kind is not MoveKind.CUT and last_kind is not MoveKind.LINK:
                    lines.append(f"F{number.format(move.feed_mm_per_min)}")
                lines.append(f"G1 {coordinates}")
            last_kind = move.kind

    lines.append("")
    lines.append("M30")
    return "\n".join(lines) + "\n"
